### ISSUE TITLE
Problems were encountered when exporting the trt model

### ISSUE THREAD

**Issue by saandasa** [OuyangJunyuan/RobDet3D#1]
I exported the onnx file using exoprt_onnx.py provided in RobDet3D for the weights you provided, but when I ran export_trt.py it generated an error that reported the following:
python tools/deploy/export_trt.py                                         --onnx tools/models/trt/iassd_hvcsx1_4x8_80e_kitti_3cls\(export\).onnx --batch 1                                                                 --type FP16
/home/xx/data/RobDet3D/rd3d/utils/base/register.py:11: UserWarning: name apply has been registered by other module
  warnings.warn(f'name {name} has been registered by other module')
load config from file: configs/iassd/iassd_4x8_80e_kitti_3cls.py
load config from module: configs.iassd.iassd_4x8_80e_kitti_3cls
[04/20/2023-17:50:15] [TRT] [W] onnx2trt_utils.cpp:367: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[04/20/2023-17:50:15] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
Traceback (most recent call last):
  File "tools/deploy/export_trt.py", line 89, in <module>
    save_path = build_engine()
  File "tools/deploy/export_trt.py", line 52, in build_engine
    parse_onnx(onnx_model, network, logger)
  File "tools/deploy/export_trt.py", line 29, in parse_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 33 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

**Comment by OuyangJunyuan** [comment]
just replace that  
https://github.com/OuyangJunyuan/RobDet3D/blob/928e47fd03555ae7110953d2d2e8bc98cb2308b1/tools/deploy/utils/load_plugins.py#L3
with your own plugin path

**Comment by saandasa** [comment]
Thank you for your reply, but I actually changed the path to the plugin file but I still have this problem.
```
import ctypes
ctypes.CDLL("/home/xx/data/pointcloud-3d-detector-tensorrt/plugins/lib/librd3d_trt_plugin.so
```

**Comment by saandasa** [comment]
> just replace that
> 
> https://github.com/OuyangJunyuan/RobDet3D/blob/928e47fd03555ae7110953d2d2e8bc98cb2308b1/tools/deploy/utils/load_plugins.py#L3
> 
> 
> with your own plugin path

I checked the exported onnx model and I found that the onnx model exported with the weights and profiles you gave me has a lot more onnx:onehot operations than the onnx model given in pointcloud-3d-detector-tensorrt, is this operation causing the error in the conversion to trt operation, is there any solution?

**Comment by OuyangJunyuan** [comment]
Please consider to pass additional `--log VERBOSE` argument and showing the message near the last error here.

**Comment by saandasa** [comment]
> Please consider to pass additional `--log VERBOSE` argument and showing the message near the last error here.

Thanks again for your reply, I used the `--verbose` command when using trtexec for onnx2trt and got the following error:
```
[04/21/2023-09:08:32] [E] [TRT] ModelImporter.cpp:774: --- Begin node ---
[04/21/2023-09:08:32] [E] [TRT] ModelImporter.cpp:775: input: "onnx::OneHot_258"
input: "onnx::OneHot_262"
input: "onnx::OneHot_259"
output: "onnx::Cast_263"
name: "OneHot_33"
op_type: "OneHot"
attribute {
  name: "axis"
  i: 1
  type: INT
}

[04/21/2023-09:08:32] [E] [TRT] ModelImporter.cpp:776: --- End node ---
[04/21/2023-09:08:32] [E] [TRT] ModelImporter.cpp:778: ERROR: builtin_op_importers.cpp:4890 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
```

I found that this was caused by not specifying the onnx version when exporting the onnx model, so I modified the export_onnx.py file and successfully exported the onnx model as well as the trt model with the following modified code:

```python
torch.onnx.export(model,
                          (batch_dict, {}),
                          output_path,
                          opset_version=11,
                          input_names=['points'],
                          output_names=['boxes', 'scores', 'nums'],
                          dynamic_axes={'points': {0: 'batch_size'},
                                        'boxes': {0: 'batch_size'},
                                        'scores': {0: 'batch_size'},
                                        'nums': {0: 'batch_size'}}
                          )
```
Thank you very much again for your help, I wonder if you are interested in adding WeChat friends, I hope to keep in touch and communicate with you on 3D object detection.

**Comment by OuyangJunyuan** [comment]
Sure, here is my WeChat ID: a706545330.

**Comment by reddittoob** [comment]
RuntimeError: Failed to parse onnx, In node 13 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

I have same error. But, I don't have plugin in my directory. how do I have to do?

**Comment by reddittoob** [comment]
Hello @OuyangJunyuan.

I tried your incredible project.

However, I got a problem. When I tried to infer my custom IA-SSD model, the result is too bad. 

So, I tried to train my custom dataset, but I got nan loss. Do you know why this problem appears?

**Comment by Waynepoo** [comment]
发生异常: RuntimeError
Failed to parse onnx, In node 13 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
  File "RobDet3D-main/tools/deploy/export_trt.py", line 29, in parse_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
  File "RobDet3D-main/tools/deploy/export_trt.py", line 52, in build_engine
    parse_onnx(onnx_model, network, logger)
  File "RobDet3D-main/tools/deploy/export_trt.py", line 89, in <module>
    save_path = build_engine()
RuntimeError: Failed to parse onnx, In node 13 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"我再转rt的时候，遇到类似的问题，请问一下这个问题怎么解决？
